name: build and deploy demoChat
# 触发脚本的条件，develop分支push代码的时候
on:
  push:
    branches:
      - main
  workflow_dispatch:
# 要执行的任务
jobs:
  # 任务名称
  build_and_deploy:
    # runs-on 指定job任务运行所需要的虚拟机环境（必填）
    runs-on: ubuntu-latest
    # 任务步骤
    steps:
      # 获取源码
      - name: 迁出代码
        # 使用action库  actions/checkout获取源码
        uses: actions/checkout@v3 # 使用的工具
      # 使用 npm
#      - name: 使用 npm
#        uses: npm/action-setup@v2
#        with:
#          version: 8.5.0
      # 安装node
      - name: 安装node.js
        # 使用action库 actions/setup-node 安装node
        uses: actions/setup-node@v3
        with:
          node-version: 16.18.1
          cache: 'npm'
      # 安装
      - name: 安装依赖
        run: npm install
      # 打包
      - name: 打包
        run: npm run build
      # 上传打包文件到远程服务器
      - name: 上传文件到远程服务器
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          username: 'root'
          password: ${{ secrets.DEPLOY_PASSWORD }}
          script: |
            # 在这里添加要执行的远程命令，例如上传文件的SCP命令
            scp -P ${{ secrets.DEPLOY_SERVER_PORT }} -r ./dist/* root@${{ secrets.DEPLOY_SERVER_HOST }}:/www/wwwroot/pan.reaicc.com

